baseURL = "https://blog.rust-jp.rs/tatsuya6502/"
languageCode = "ja-JP"
title = "Oxidized Bookshelf"

pygmentsCodeFences = true

theme = "hugo_theme_pickles"
# theme = "hugo-material-blog"
# theme = "hugo-paper"

publishDir = "docs"

# Copyright notice. This is displayer in the footer.
copyright = "&copy; 2019 Tatsuya Kawano (tatsuya6502)"
# custom_css = "/static/css/custom.css"

[params]
  # Short subtitle/tagline. This is displayed in the header.
  subtitle = "プログラミング言語 Rust について気の向くままに綴っていきます | tatsuya6502"

  paginate = 10
  # Social accounts. Link to these accounts are displayed in the header and footer
  # twitter = "tatsuya6502"
  # facebook = "Your Facebook username"
  # instagram = "Your Instagram username"
  github = "tatsuya6502"
  gitlab = "tatsuya6502"
  # npm = "Your npm username"
  # codepen = "Your CodePen username"
  # dribbble = "Your Dribbble username"
  # fivehundredpx = "Your 500px username" # 500px
  # flickr = "Your Flickr username"
  # pinterest = "Your Pinterest username"
  # tumblr = "Your Tumblr username"
  # vimeo = "Your Vimeo username"
  # youtube = "Your YouTube username"
  # linkedin = "Your LinkedIn username"
  # Disqus shortname
  # disqus = ""
  # Google Analytics API key.
  # ga_api_key = "Your Google Analytics tracking id"

  author = "Tatsuya Kawano (tatsuya6502)"
  # authorwebsite = "example.com"
  # avatar = "/path/to/avatar"
  # contact = "Your contact link (ex. mailto:foo@example.com)"
  bio = "Erlang/OTPやRustで分散DBを開発してます。最近、Rustの本を書きました。上海在住"
  # Logo image. This is displayed ogp image.
  # logo = "/path/to/logo"
  # favicon = "/path/to/favicon"

[[menu.main]]
    name = "Categories"
    url = "/categories"
    weight = 1

[[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = 2

# [[menu.main]]
#     name = "About"
#     url = "/about"
#     weight = 3

[[menu.main]]
    name = "RSS"
    url = "/index.xml"
    weight = 4

[related]
  # Only include matches with rank >= threshold. This is a normalized rank between 0 and 100.
  threshold = 80

  # To get stable "See also" sections we, by default, exclude newer related pages.
  includeNewer = false

  # Will lower case keywords in both queries and in the indexes.
  toLower = false

  [[related.indices]]
  name = "keywords"
  weight = 150
  [[related.indices]]
  name  = "author"
  toLower = true
  weight = 30
  [[related.indices]]
  name  = "tags"
  weight = 100
  [[related.indices]]
  name  = "date"
  weight = 10
  pattern = "2017"
